services:
  whisper-service:
    build:
      context: ./whisper/
      dockerfile: Dockerfile
    container_name: whisper-service
    ports:
      - "8081:8080"
    volumes:
      - whisper-models:/opt/whisper.cpp/models
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    networks:
      - speak-to-input-network
      - share_network

  api-service:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: speak-to-input
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env
    networks:
      - speak-to-input-network
      - share_network

volumes:
  whisper-models:
    driver: local

networks:
  speak-to-input-network:
    driver: bridge
  share_network:
    driver: bridge
